name: newspaper_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #icon
  font_awesome_flutter: ^10.5.0
  ionicons: ^0.2.2

  #state management
  flutter_bloc: ^8.1.2

  #comparing dart objects
  equatable: ^2.0.5

  #service locator
  get_it: ^7.6.0

  #dateFormat
  intl: ^0.18.1

  #Database
  floor: any

  #make request to api
  retrofit: ^4.0.1

  #Hooks
  flutter_hooks: ^0.20.0

  #chached image
  cached_network_image: ^3.2.0

  dartz: ^0.10.1

  flutter_svg: ^2.0.7

  shared_preferences: ^2.0.18

  flash: ^2.0.5+1

  flutter_spinkit: ^5.1.0

  connectivity_plus: ^4.0.1

  flutter_screenutil: ^5.5.3+2

  image_picker: ^0.8.7+5

  fluttertoast: ^8.2.1

  network_image: ^0.1.1

  #firebase
  firebase_core:
  firebase_auth: ^4.6.1
  cloud_firestore: ^4.7.1
  firebase_storage: ^11.2.1
  google_sign_in: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  retrofit_generator: 7.0.8
  floor_generator: 1.4.2
  build_runner: 2.4.6


flutter:

  uses-material-design: true


  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
